spring:
   jpa:
     show-sql: true
   datasource:
     url: jdbc:mysql://localhost:3306/emp_management_system?useSSL=false&serverTimezone=Europe/Warsaw
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
     password: admin
   liquibase:
     contexts: prod

